### ISSUE TITLE
002chainer/004: Functionを利用するには，そのcallオブジェクトを呼び出します。 

### ISSUE THREAD

**Issue by msakai** [chainer/pg-dl-tutorial#21]
https://play.chainer.org/book/1/2/5

> Functionを利用するには，そのcallオブジェクトを呼び出します。 

正しくは「Functionを利用するには，その__call__メソッドを呼び出します」などでしょうか？

**Comment by okuta** [comment]
指摘ありがとうございます。
「__call__メソッドを呼び出します」と書くと、直接 `obj.__call__()` と初心者がかきそうなので、「Functionを利用するには，Functionのインスタンスを作成後に関数として呼びだします。」としてみました。
ちょっとわかりにくい感じもするので、アイデアがあれば歓迎します。

**Comment by msakai** [comment]
それで問題ないと思います。
